# PIPELINE DEFINITION
# Name: pipeline
components:
  comp-test:
    executorLabel: exec-test
  comp-train:
    executorLabel: exec-train
deploymentSpec:
  executors:
    exec-test:
      container:
        command:
        - python3
        - segmentation/unet/test_with_hydra.py
        image: unet:v0.1.0
    exec-train:
      container:
        command:
        - python3
        - segmentation/unet/train_with_hydra.py
        image: unet:v0.1.0
pipelineInfo:
  name: pipeline
root:
  dag:
    tasks:
      test:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-test
        dependentTasks:
        - train
        taskInfo:
          name: test
      train:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-train
        taskInfo:
          name: train
schemaVersion: 2.1.0
sdkVersion: kfp-2.13.0
