
version: "3.8"

services:
  rag-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: rag:v0.1.0
    working_dir: /app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HOST=0.0.0.0
    volumes:
      - .:/app
    ports:
      - 1234:8000
    stdin_open: true 
    tty: true
  rag-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: rag:v0.1.0
    working_dir: /app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HOST=0.0.0.0
    ports:
      - 1234:8000
