FROM python:3.12-slim

RUN apt-get update &&  \
    apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && pip install poetry

COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false && poetry install --no-root --no-interaction --no-ansi

WORKDIR /app
COPY . .

CMD [ "python", "server.py" ]
